---
- hosts: localhost
  connection: local

  vars_files: 
  - './group_vars/creds.yml'
 
  tasks:
  - name: Export from controller
    ansible.controller.export:
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      users: all
      validate_certs: false
    register: teams_export
    tags: 
    - export
    - format

  - name: debug teams_export
    debug:
      var: teams_export.assets.users
#    when: ansible_verbosity > 1 
    tags: 
    - export
    - format

  - name: import and format the teams_export    
    controller_audit:
      audit_item: users
      resources: "{{ teams_export.assets.users }}"
    register: user_roles
    tags: format

  - name: debug teams_export
    debug:
      var: user_roles 
    tags: format
